name: Deploy para GitHub Pages Público

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Copiar arquivos reais
        run: |
          mkdir -p dist
          cp -r index.html css scripts images Pages dist/

      - name: Deploy para repositório público
        uses: peaceiris/actions-gh-pages@v3
        with:
          external_repository: Josi014/Manual_Efesus_public
          publish_dir: ./dist
          personal_token: ${{ secrets.PUBLISH_TOKEN }}
          publish_branch: main
